### ISSUE TITLE
Microphone/camera detection

### ISSUE THREAD

**Issue by tomdaly** [josh/Aware#68]
I primarily use Aware to make sure that I'm getting up from my desk once an hour, and it's perfect for when I'm writing code and using my machine. The only place it falls short is in meetings - often I'm not touching my keyboard and mouse if I'm on a Zoom call, which means the timer will reset.

Is there any way to detect if either the microphone is being actively used or if the camera is on? I understand if this is not possible as it might require access to the microphone/camera permissions which could be a privacy issue. As a fallback, is it possible to detect if an application is full-screen and not reset the timer if so? (though I can see this causing other issues with video playback/screensavers etc.)

**Comment by josh** [comment]
Yes, I've definitely ran into this myself. I was hoping for some kind of API to detect video playing on screen, but no such thing appears to exist. Trying to access the microphone or camera APIs in this way would surely be a Mac App Store rejection, so that's not a direction I'd like to take. Totally okay if you want to fork the project and built a variant that does this for your own personal use.

I will be keeping on eye on macOS updates for APIs that could potentially solve this issue! Thanks for writing in.
